DROP TABLE IF EXISTS player_unlocked_animals CASCADE;

CREATE TABLE player_unlocked_animals (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE NOT NULL,
  date_earned TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);