DROP TABLE IF EXISTS quests CASCADE;

CREATE TABLE quests (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  img_url VARCHAR(255) NOT NULL,
  goal INTEGER NOT NULL,
  goal_units VARCHAR(255) NOT NULL,
  reward_id INTEGER REFERENCES rewards(id) ON DELETE CASCADE NOT NULL
);