DROP TABLE IF EXISTS game_challenges CASCADE;
CREATE TABLE game_challenges (
  id SERIAL PRIMARY KEY NOT NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE NOT NULL DEFAULT CURRENT_DATE,
  quest_id integer REFERENCES quests(id) ON DELETE CASCADE NOT NULL,
  challenges_type VARCHAR(255) NOT NULL
);